#+TITLE: Syllabus - STAT 2255: Statistical Programming, Spring 2025

* Course and Instructor Information

- Course Title: Statistical Programming
- Credits: 3.0
- Format: In-person lecture (TuTh 9:30AM-10:45AM, AUST 434)
- Prerequisites: MATH 1132Q, or instructor consent. Recommended preparation: CSE 1010 or prior programming experience. 
- Professor: Dr. Wenrui Li
- Pronouns: she/her/hers
- Email: [[mailto:wenrui.li@uconn.edu][wenrui.li@uconn.edu]]
- Office Hours: TuTh 11:00AM - 12:00PM in AUST 304, or by appointment

- Grader: Riyanka Bhowal (email: dvk24005@uconn.edu)

* Course Materials
Participation in this course requires the use of a personal computer such as a laptop or a desktop. The University has set minimum 
[[https://kb.uconn.edu/space/IKB/10852500927/Student+Device+Requirements][device requirements for all students]].

We will use the open-source software Python. An easy way to setup Python is to use [[https://docs.conda.io/en/latest/][conda]] by installing [[https://docs.conda.io/en/latest/miniconda.html][miniconda]] or
[[https://www.anaconda.com/download/][anaconda]]. Here is are some comparisons between the two distribution [[https://conda.io/projects/conda/en/latest/user-guide/install/download.html#anaconda-or-miniconda][anaconda vs
miniconda]]. Download [[https://www.anaconda.com/download/success][installers]].

# If you'd prefer that conda's base environment not be activated on startup,
# set the auto_activate_base parameter to false:
# conda config --set auto_activate_base false

Notes for this course will be posted on the GitHub repo: https://github.com/LiTeaching/STAT2255. There is no required textbook. Recommended text includes
- The Python Tutorial: available from the Python website https://docs.python.org/3/tutorial/. This is a dense but complete overview of the most important parts of the language.
- Style Guide for Python Code: available from the Python website http://www.python.org/dev/peps/pep-0008/. This is the official style guide to Python, and it contains many helpful programming tips.
- Think Stats - Exploratory Data Analysis in Python: freely available online at https://greenteapress.com/wp/think-stats-2e/.

* Course Description
Introduction to statistical programming via Python including data types, control
flow, object-oriented programming, and graphical user interface-driven
applications such as Jupyter notebooks. Emphasis on algorithmic thinking,
efficient implementation of different data structures, control and data
abstraction, file processing, and data analysis and visualization.

* Course Objectives
By the end of the semester, students should be able to: write efficient functions and classes;
perform data analysis and manipulation using Pandas package;
conduct one-sample and two-sample hypothesis testings;
produce customized statistical graphics using Matplotlib package;
write Python code to generate random numbers.

* Course Outline (subject to change)

1. Virtual Environment, Markdown (1 week) 
2. Object Types and Statements (2 week) 
3. Modules (1 week)
4. Numpy (1 week)
5. Object-Oriented Programming (1 week)
6. Testing and Exception Handling (1 week)
7. Running Time Analysis (1 week)
8. Root Finding (1 week)
9. Pandas (2 week)
10. Data Visualization and Hypothesis Testing (1 week)
11. Random Variable Generation (1 week)


* Course Requirements and Grading

*Summary of Course Grading:*

| Course Components         | Weight |
|---------------------------+--------|
| Homework       	    |    25% |
| Quiz 	                    |    5%  |
| Midterm                   |    30% |
| Final                     |    40% |
|---------------------------+--------|

*Homework*

Homework is a critical part of the course and will help you learn the material. Homework is assigned approximately once every two weeks, with the due dates listed on HuskyCT. Unless otherwise specified, homework should be submitted through HuskyCT. Homework submissions must contains a .pdf file along with source code in .ipynb, .md, or .py format. Late submissions within the 2-day grace period will only be worth 50% - 95% of the points. Submissions beyond 2 days will not be graded and will receive no credit. No homework grade will be dropped. Large penalties will be applied to any homework submission exhibiting duplication, copying of solutions, or code generated by large language models such as ChatGPT. See UConn's Academic Integrity policy below.

Generate pdf files: You need [[https://pandoc.org/][pandoc]] and xelatex to export pdf files from jupyter book. 
- Install pandoc and xelatex
  - Download and install pandoc [[https://github.com/jgm/pandoc/releases/latest][here]]. Choose the .pkg version for Mac and the .msi version for Windows.
  - Download and install [[https://miktex.org/download][MiKTeX]] (better with Windows) or [[https://tug.org/mactex/][MacTeX]] (Mac only).
  - You may need to restart your anaconda prompt and/or shell for the two newly installed software to work. 
  - With MiKTeX the first time you export a pdf file, you need to wait for a while, because it needs to fetch necessary packages online.
- A temp ad-hoc solution -- print the webpage: be sure to adjust the width of your browser to make the pdf print look better.

*Quiz*

Pop quizzes may be given at any time during the semester. If you have to miss a lecture, you have to let me know before the class so that I will use the average
of other quizzes to replace a missed quiz score. Otherwise, you will receive a 0 for a missed quiz.

*Midterm Exam* 

Midterm exam will consist of multiple choice questions, true/false questions and short answer questions. It will be held in class on March 13. The midterm exam is closed book and closed notes. No make-up exam. Exceptions may be considered in case of an emergency that is documented (in writing) by the Dean of Students Office, Office of Student Services and Advocacy, Health Center, or other university official.

*Final Exam* 

There will be one final exam during the exam week. It is open book and open notes. Questions will primarily involve generating random numbers, hypothesis testing, visualizing, and analyzing data. The exam should be submitted through HuskyCT. Final exam submissions must contains a .pdf file along with source code in .ipynb, .md, or .py format. No make-up exam. Exceptions may be considered in case of an emergency that is documented (in writing) by the Dean of Students Office, Office of Student Services and Advocacy, Health Center, or other university official. 

*Grading Scale:*

Information on grades and grading can be found on the Registrar’s site and in the catalog:
- [[https://registrar.uconn.edu/grades/][Registrar’s Information on Grading Scales]]
- [[https://catalog.uconn.edu/undergraduate/#Grades][Undergraduate Catalog Course Grades and Information]]

General explanation of the meaning of grades:

| Explanation               | Letter Grade |    Range  	 |
|---------------------------+--------------+-------------|
| Distinction      	    |      A       |   [90,100]  | 
| 	                    |      A-      |   [88,90)   | 
| Good Quality      	    |      B+      |   [83,88)   | 
|  		      	    |      B       |   [78,83)   | 
|  		      	    |      B-      |   [74,78)   |
| Below Expected Standard   |      C+      |   [69,74)   |
|  		      	    |      C       |   [64,69)   | 
|  		      	    |      C-      |   [60,64)   |
| Unsatisfactory Quality    |      D+      |   [57,60)   |
|  		      	    |      D       |   [53,57)   |
|  		      	    |      D-      |   [50,53)   |
|  	Failure  	    |      F       |   [0,50)    |
|---------------------------+--------------+-------------|

Final scores will be curved if deemed necessary by the instructor. 

*Feedback and Grades:*

The grader strives to post grades on HuskyCT within one week of homework deadlines and quizzes. Exam grades will be released within one week after the exam closes. 

*Due Dates and Late Policy:*

All course due dates are identified in their respective submission portals on HuskyCT. Deadlines are based on Eastern Time; if you are in a different time zone, please adjust your submittal times accordingly. The instructor reserves the right to change dates accordingly as the semester progresses. All changes will be communicated in an appropriate manner.

*Weekly Time Commitment:*

You should expect to dedicate approximately 9 - 12 hours a week to this course. This expectation is based on the various course activities, assignments, and assessments and the University of Connecticut’s policy regarding credit hours.

* Student Responsibilities and Resources

As a member of the University of Connecticut student community, you are held to certain standards and academic
policies. In addition, there are numerous resources available to help you succeed in your academic work. 
Review these important [[https://onlinestudent.uconn.edu/learn--more/#POL][standards, policies and resources]], which include:
- The Student Code
  - Resources on Avoiding Cheating and Plagiarism
- [[https://policy.uconn.edu/2023/07/11/academic-scholarly-and-professional-integrity-and-misconduct-aspim-policy-on/][Academic, Scholarly, and Professional Integrity and Misconduct (ASPIM)]]
- Copyrighted Materials
- Credit Hours and Workload
- Netiquette and Communication
- Adding or Dropping a Course
- Academic Calendar
- Policy Against Discrimination, Harassment and Inappropriate Romantic Relationships
- Sexual Assault Reporting Policy


* About Generative AI
Be careful when using generative AI such as ChatGPT, CoPilot, and Gemini. They
can be helpful for checking your code or explaining codes you don't understand,
but they should not be relied upon to generate your code. It's crucial to fully
understand the code you write and be able to code without access to generative
AI.

* Academic Integrity

A fundamental tenet of all educational institutions is academic honesty;
academic work depends upon respect for and acknowledgement of the research and
ideas of others. Misrepresenting someone else's work as one's own is a serious
offense in any academic setting and it will not be condoned. Academic misconduct
includes, but is not limited to, providing or receiving assistance in a manner
not authorized by the instructor in the creation of work to be submitted for
academic evaluation (e.g. papers, projects, and examinations); any attempt to
influence improperly (e.g. bribery, threats) any member of the faculty, staff,
or administration of the University in any matter pertaining to academics or
research; presenting, as one's own,the ideas or words of another for academic
evaluation; doing unauthorized academic work for which another person will
receive credit or be evaluated; and presenting the same or substantially the
same papers or projects in two or more courses without the explicit permission
of the instructors involved. A student who knowingly assists another student in
committing an act of academic misconduct shall be equally accountable for the
violation, and shall be subject to the sanctions and other remedies described in
The Student Code.


* Student Health and Wellness

The University of Connecticut strives to support the optimal well-being of all students. [[https://studenthealth.uconn.edu][Student Health and
Wellness]] (SHaW) offers a comprehensive set of services including medical care, mental health, and health
promotion.

* Students with Disabilities

The University of Connecticut is committed to protecting the rights of individuals with disabilities and assuring that the learning environment is accessible. Students who require accommodations should contact the Center for Students with Disabilities, Wilbur Cross Building Room 204, (860) 486-2020 or http://csd.uconn.edu/.

Blackboard measures and evaluates accessibility using two sets of standards: the WCAG 2.0 standards issued by the World Wide Web Consortium (W3C) and Section 508 of the Rehabilitation Act issued in the United States federal government.” (Retrieved March 24, 2013 from [[https://www.anthology.com/products/teaching-and-learning/learning-effectiveness/blackboard][Blackboard's website]])

* Software/Technical Requirements (with Accessibility and Privacy Information)

The University has set minimum [[https://kb.uconn.edu/space/IKB/10852500927/Student+Device+Requirements][device requirements for all students]]. NOTE: Chromebooks do not meet the minimum requirements.

The software/technical requirements for this course include:
- HuskyCT/Blackboard ([[https://www.anthology.com/our-commitment-to-accessibility][HuskyCT/ Blackboard Accessibility Statement]], [[https://www.anthology.com/trust-center/privacy-statement][HuskyCT/ Blackboard Privacy Policy]])
- [[https://get.adobe.com/reader/][Adobe Acrobat Reader]] ([[https://helpx.adobe.com/adobe-connect/using/accessibility-features.html][Adobe Reader Accessibility Statement]], [[https://www.adobe.com/privacy.html][Adobe Reader Privacy Policy]])
- Python
- Dedicated access to high-speed internet with a minimum speed of 1.5 Mbps (4 Mbps or higher is recommended).

For information on managing your privacy at the University of Connecticut, visit the [[https://privacy.uconn.edu][University’s Privacy page]].

* Help

The [[https://kb.uconn.edu/space/TL/10763764102/Student+Support][IT Knowledge Base]] provides students with support, troubleshooting, and how-to information about HuskyCT. The [[https://kb.uconn.edu/space/TL/10763764102/Student+Support][IT Knowledge Base]] includes a video tour of HuskyCT.

For technical help with HuskyCT, you have access to the in-person/live person support options available during
regular business hours through the [[https://techsupport.uconn.edu][Technology Support Center]]. You also have [[https://uconn.edusupportcenter.com/shp/U_Conn/home][24x7 Course Support]] outside of business hours, including access to live chat, phone, and support documents.

* Study Groups

Are you interested in forming a study group with other students in the class? There is a [[https://nexus.uconn.edu/secure_per/studygroups/index.php][study group application]] in Nexus that can help you get started. View this [[https://nexus.uconn.edu/secure_per/studygroups/video.php][video]] for more information.

* Minimum Technical Skills

To be successful in this course, you will need the following technical skills:
- Use electronic mail with attachments.
- Copy and paste text, graphics or hyperlinks.
- Work within two or more browser windows simultaneously.
- Access PDF files.

* Evaluation of the Course

Students will be provided an opportunity to evaluate instruction in this course using the University's [[https://bpir.uconn.edu/home/institutional-research/set/][Student Experience of Teaching (SET)]], which is administered by the [[https://bpir.uconn.edu][Office of Budget, Planning and Institutional Research]] (BPIR).

Additional informal formative surveys may also be administered within the course as an optional evaluation tool.


* Disclaimer

The instructor reserves the right to make changes to the syllabus as
necessitated by circumstances.

#+startup: show3levels hideblocks
#+options: h:4 timestamp:nil date:nil tasks tex:t num:t toc:nil
#+options: author:nil creator:nil html-postamble:nil HTML_DOCTYPE:HTML5
#+EXPORT_FILE_NAME: syllabus
#+HTML_HEAD: <base target="_blank">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://ossifragus.github.io/style/github-pandoc.css"/>
#+LaTeX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt, hidelinks]
#+latex_header: \usepackage[margin=1in]{geometry}

